// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modelo;

#nullable disable

namespace Modelo.Migrations
{
    [DbContext(typeof(BoleteriaContext))]
    [Migration("20241112215400_InitialCreate2")]
    partial class InitialCreate2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Modelo.Colectivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Linea")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Colectivo");
                });

            modelBuilder.Entity("Modelo.Pasajero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ColectivoId")
                        .HasColumnType("int");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ColectivoId");

                    b.ToTable("Pasajeros");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Modelo.PasajeroEstudiante", b =>
                {
                    b.HasBaseType("Modelo.Pasajero");

                    b.Property<int>("Legajo")
                        .HasColumnType("int");

                    b.Property<string>("Universidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("PasajerosEstudiantes", (string)null);
                });

            modelBuilder.Entity("Modelo.Pasajero", b =>
                {
                    b.HasOne("Modelo.Colectivo", null)
                        .WithMany("Pasajeros")
                        .HasForeignKey("ColectivoId");
                });

            modelBuilder.Entity("Modelo.PasajeroEstudiante", b =>
                {
                    b.HasOne("Modelo.Pasajero", null)
                        .WithOne()
                        .HasForeignKey("Modelo.PasajeroEstudiante", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modelo.Colectivo", b =>
                {
                    b.Navigation("Pasajeros");
                });
#pragma warning restore 612, 618
        }
    }
}
